### ISSUE TITLE
we need to integrate your project into cloudmesh-cloud

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/sp19-516-133#3]

**Comment by amannars** [comment]
Hello Dr.Laszewski, We did this on the 25th of April during the office hours call.

**Comment by laszewsk** [comment]
great. Remember I have lost of project and sometimes things slip my mind or I get notified by others that ask this question. SO I hope everything is ok.

**Comment by laszewsk** [comment]
This is being cause by your readme not being upto date?

**Comment by amannars** [comment]
Hello Dr.Laszewski, That is right. I have overlooked one of the links is not up to date because of the changes we made. I have updated the links to all the section, chapter and project.
